apiVersion: v1
kind: Service
metadata:
  name: blob-worker
spec:
  selector:
    app: blob-worker
  ports:
    - name : worker-service
      port: 3000
      targetPort: 3000
    - name : blob-service
      port: 3001
      targetPort: 3001
  type: LoadBalancer